In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv('Laliga.csv') 
df.head()

  Unnamed: 0       Unnamed: 1  ...    Unnamed: 18   Unnamed: 19
0        Pos             Team  ...  Since/LastApp  BestPosition
1          1      Real Madrid  ...           1929             1
2          2        Barcelona  ...           1929             1
3          3  Atletico Madrid  ...        2002-03             1
4          4         Valencia  ...        1987-88             1

[5 rows x 20 columns]

In [2]:
header_row=0
df.columns= df.iloc[header_row]

In [3]:
df=df.drop(header_row)

In [4]:
df=df.reset_index(drop=True)

In [5]:
df=df.replace('-',0)

In [6]:
df['Debut']=df['Debut'].str.slice(stop=4)
df['Debut']=pd.to_numeric(df['Debut'],errors='coerce')

In [7]:
data=df[(df['Debut']>=1930)]

In [8]:
data=data[(data['Debut']<=1980)]

Task 1

In [9]:
data

0  Pos                 Team Seasons  ... Debut Since/LastApp BestPosition
3    4             Valencia      82  ...  1931       1987-88            1
5    6              Sevilla      73  ...  1934       2001-02            1
8    9             Zaragoza      58  ...  1939       2012-13            2
9   10           Real Betis      51  ...  1932       2015-16            1
10  11  Deportivo La Coruna      45  ...  1941       2014-15            1
11  12           Celta Vigo      51  ...  1939       2012-13            4
12  13           Valladolid      42  ...  1948       2013-14            4
14  15       Sporting Gijon      43  ...  1944       2015-16            2
15  16              Osasuna      37  ...  1935       2016-17            4
16  17               Malaga      36  ...  1949       2008-09            4
17  18               Oviedo      38  ...  1933       2000-01            3
18  19             Mallorca      27  ...  1960       2012-13            3
19  20           Las Palmas      33  ...  1951       2015-16            2
21  22              Granada      23  ...  1941       2016-17            6
22  23       Rayo Vallecano      17  ...  1977       2015-16            8
23  24                Elche      21  ...  1959       2014-15            5
25  26             Hercules      20  ...  1935       2010-11            5
26  27             Tenerife      13  ...  1961       2009-10            5
27  28               Murcia      18  ...  1940       2007-08           11
28  29               Alaves      12  ...  1930       2016-17            6
29  30              Levante      11  ...  1963       2015-16            6
30  31            Salamanca      12  ...  1974       1998-99            7
31  32             Sabadell      14  ...  1943       1987-88            4
32  33                Cadiz      12  ...  1977       2005-06           12
34  35            Castellon      11  ...  1941       1990-91            4
37  38              Cordoba       9  ...  1962       2014-15            5
39  40           Recreativo       5  ...  1978       2008-09            8
40  41            Burgos CF       6  ...  1971       1979-80           12
41  42           Pontevedra       6  ...  1963       1969-70            7
46  47            Gimnastic       4  ...  1947       2006-07            7
49  50             Alcoyano       4  ...  1945       1950-51           10
50  51                 Jaen       3  ...  1953       1957-58           14
52  53           AD Almeria       2  ...  1979       1980-81           10
54  55               Lleida       2  ...  1950       1993-94           16
57  58               Condal       1  ...  1956       1956-57           16
58  59      Atletico Tetuan       1  ...  1951       1951-52           16
59  60     Cultural Leonesa       1  ...  1955       1955-56           15

[37 rows x 20 columns]

Task 2

In [10]:
df['Points']=pd.to_numeric(df['Points'],errors='coerce')
df.sort_values(by='Points',ascending=False)
df.head()

0 Pos             Team Seasons  Points  ...   T Debut Since/LastApp BestPosition
0   1      Real Madrid      86    4385  ...  79  1929          1929            1
1   2        Barcelona      86    4262  ...  83  1929          1929            1
2   3  Atletico Madrid      80    3442  ...  56  1929       2002-03            1
3   4         Valencia      82    3386  ...  50  1931       1987-88            1
4   5  Athletic Bilbao      86    3368  ...  49  1929          1929            1

[5 rows x 20 columns]

In [11]:
def Goal_diff_count(GoalsFor, GoalsAgainst ):
  Goal_diff=GoalsFor-GoalsAgainst
  return Goal_diff

In [12]:
df['GoalsFor']=pd.to_numeric(df['GoalsFor'],errors='coerce')
df['GoalsAgainst']=pd.to_numeric(df['GoalsAgainst'],errors='coerce')
df.head()

0 Pos             Team Seasons  Points  ...   T Debut Since/LastApp BestPosition
0   1      Real Madrid      86    4385  ...  79  1929          1929            1
1   2        Barcelona      86    4262  ...  83  1929          1929            1
2   3  Atletico Madrid      80    3442  ...  56  1929       2002-03            1
3   4         Valencia      82    3386  ...  50  1931       1987-88            1
4   5  Athletic Bilbao      86    3368  ...  49  1929          1929            1

[5 rows x 20 columns]

In [13]:
df['Goal_diff']=df.apply(lambda x: Goal_diff_count(x['GoalsFor'],x['GoalsAgainst']),axis=1)
df.head()

0 Pos             Team Seasons  ...  Since/LastApp BestPosition Goal_diff
0   1      Real Madrid      86  ...           1929            1      2807
1   2        Barcelona      86  ...           1929            1      2786
2   3  Atletico Madrid      80  ...        2002-03            1      1225
3   4         Valencia      82  ...        1987-88            1       929
4   5  Athletic Bilbao      86  ...           1929            1       931

[5 rows x 21 columns]

In [14]:
df[df['Goal_diff']==df['Goal_diff'].max()][['Team','Goal_diff']]

0         Team  Goal_diff
0  Real Madrid       2807

In [15]:
df[df['Goal_diff']==df['Goal_diff'].min()][['Team','Goal_diff']]

0               Team  Goal_diff
13  Racing Santander       -525

In [16]:
df['GamesWon']=pd.to_numeric(df['GamesWon'])
df['GamesPlayed']=pd.to_numeric(df['GamesPlayed'])
df['Win_percent']=(df['GamesWon']/df['GamesPlayed'])*100
df.head()

0 Pos             Team Seasons  ...  BestPosition  Goal_diff  Win_percent
0   1      Real Madrid      86  ...             1       2807    59.630702
1   2        Barcelona      86  ...             1       2786    57.241130
2   3  Atletico Madrid      80  ...             1       1225    47.475134
3   4         Valencia      82  ...             1        929    44.557057
4   5  Athletic Bilbao      86  ...             1        931    43.772629

[5 rows x 22 columns]

In [17]:
df['Win_percent']=df['Win_percent'].fillna(value=0)

In [18]:
df.sort_values(by='Win_percent',ascending=False)

0  Pos              Team Seasons  ...  BestPosition  Goal_diff  Win_percent
0    1       Real Madrid      86  ...             1       2807    59.630702
1    2         Barcelona      86  ...             1       2786    57.241130
2    3   Atletico Madrid      80  ...             1       1225    47.475134
3    4          Valencia      82  ...             1        929    44.557057
4    5   Athletic Bilbao      86  ...             1        931    43.772629
..  ..               ...     ...  ...           ...        ...          ...
55  56           Leganes       1  ...            17        -19    21.052632
56  57             Xerez       1  ...            20        -28    21.052632
54  55            Lleida       2  ...            16       -112    19.117647
59  60  Cultural Leonesa       1  ...            15        -31    16.666667
60  61            Girona       1  ...             9          0     0.000000

[61 rows x 22 columns]

In [19]:
df.groupby(by='BestPosition')['Points'].sum

In [21]:
for i, i in df.groupby('BestPosition'):
    print(i)
    print(i)
    print('\n')

0  Pos                 Team Seasons  ...  BestPosition  Goal_diff  Win_percent
0    1          Real Madrid      86  ...             1       2807    59.630702
1    2            Barcelona      86  ...             1       2786    57.241130
2    3      Atletico Madrid      80  ...             1       1225    47.475134
3    4             Valencia      82  ...             1        929    44.557057
4    5      Athletic Bilbao      86  ...             1        931    43.772629
5    6              Sevilla      73  ...             1        307    41.112957
7    8        Real Sociedad      70  ...             1         -2    37.532580
9   10           Real Betis      51  ...             1       -333    35.069444
10  11  Deportivo La Coruna      45  ...             1       -136    36.797386

[9 rows x 22 columns]
0  Pos                 Team Seasons  ...  BestPosition  Goal_diff  Win_percent
0    1          Real Madrid      86  ...             1       2807    59.630702
1    2            Barcelona      86  ...             1       2786    57.241130
2    3      Atletico Madrid      80  ...             1       1225    47.475134
3    4             Valencia      82  ...             1        929    44.557057
4    5      Athletic Bilbao      86  ...             1        931    43.772629
5    6              Sevilla      73  ...             1        307    41.112957
7    8        Real Sociedad      70  ...             1         -2    37.532580
9   10           Real Betis      51  ...             1       -333    35.069444
10  11  Deportivo La Coruna      45  ...             1       -136    36.797386

[9 rows x 22 columns]


0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
38  39  Compostela       4  ...            10        -42    32.500000
43  44       Eibar       3  ...            10        -28    30.701754
49  50    Alcoyano       4  ...            10       -107    27.777778
52  53  AD Almeria       2  ...            10        -45    25.000000

[4 rows x 22 columns]
0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
38  39  Compostela       4  ...            10        -42    32.500000
43  44       Eibar       3  ...            10        -28    30.701754
49  50    Alcoyano       4  ...            10       -107    27.777778
52  53  AD Almeria       2  ...            10        -45    25.000000

[4 rows x 22 columns]


0  Pos    Team Seasons  ...  BestPosition  Goal_diff  Win_percent
27  28  Murcia      18  ...            11       -385    24.744027

[1 rows x 22 columns]
0  Pos    Team Seasons  ...  BestPosition  Goal_diff  Win_percent
27  28  Murcia      18  ...            11       -385    24.744027

[1 rows x 22 columns]


0  Pos       Team Seasons  ...  BestPosition  Goal_diff  Win_percent
32  33      Cadiz      12  ...            12       -269    23.214286
40  41  Burgos CF       6  ...            12        -94    28.921569

[2 rows x 22 columns]
0  Pos       Team Seasons  ...  BestPosition  Goal_diff  Win_percent
32  33      Cadiz      12  ...            12       -269    23.214286
40  41  Burgos CF       6  ...            12        -94    28.921569

[2 rows x 22 columns]


0  Pos  Team Seasons  Points  ...  Since/LastApp  BestPosition Goal_diff Win_percent
50  51  Jaen       3      71  ...        1957-58            14       -62   32.222222

[1 rows x 22 columns]
0  Pos  Team Seasons  Points  ...  Since/LastApp  BestPosition Goal_diff Win_percent
50  51  Jaen       3      71  ...        1957-58            14       -62   32.222222

[1 rows x 22 columns]


0  Pos              Team Seasons  ...  BestPosition  Goal_diff  Win_percent
59  60  Cultural Leonesa       1  ...            15        -31    16.666667

[1 rows x 22 columns]
0  Pos              Team Seasons  ...  BestPosition  Goal_diff  Win_percent
59  60  Cultural Leonesa       1  ...            15        -31    16.666667

[1 rows x 22 columns]


0  Pos             Team Seasons  ...  BestPosition  Goal_diff  Win_percent
54  55           Lleida       2  ...            16       -112    19.117647
57  58           Condal       1  ...            16        -20    23.333333
58  59  Atletico Tetuan       1  ...            16        -34    23.333333

[3 rows x 22 columns]
0  Pos             Team Seasons  ...  BestPosition  Goal_diff  Win_percent
54  55           Lleida       2  ...            16       -112    19.117647
57  58           Condal       1  ...            16        -20    23.333333
58  59  Atletico Tetuan       1  ...            16        -34    23.333333

[3 rows x 22 columns]


0  Pos         Team Seasons  ...  BestPosition  Goal_diff  Win_percent
42  43     Numancia       4  ...            17        -98    24.342105
47  48  Extremadura       2  ...            17        -55    25.000000
55  56      Leganes       1  ...            17        -19    21.052632

[3 rows x 22 columns]
0  Pos         Team Seasons  ...  BestPosition  Goal_diff  Win_percent
42  43     Numancia       4  ...            17        -98    24.342105
47  48  Extremadura       2  ...            17        -55    25.000000
55  56      Leganes       1  ...            17        -19    21.052632

[3 rows x 22 columns]


0  Pos    Team Seasons  ...  BestPosition  Goal_diff  Win_percent
48  49  Merida       2  ...            19        -45        23.75

[1 rows x 22 columns]
0  Pos    Team Seasons  ...  BestPosition  Goal_diff  Win_percent
48  49  Merida       2  ...            19        -45        23.75

[1 rows x 22 columns]


0  Pos              Team Seasons  ...  BestPosition  Goal_diff  Win_percent
8    9          Zaragoza      58  ...             2       -164    35.146022
13  14  Racing Santander      44  ...             2       -525    31.722689
14  15    Sporting Gijon      43  ...             2       -399    32.304527
19  20        Las Palmas      33  ...             2       -399    33.485401
20  21        Villarreal      17  ...             2        103    41.176471

[5 rows x 22 columns]
0  Pos              Team Seasons  ...  BestPosition  Goal_diff  Win_percent
8    9          Zaragoza      58  ...             2       -164    35.146022
13  14  Racing Santander      44  ...             2       -525    31.722689
14  15    Sporting Gijon      43  ...             2       -399    32.304527
19  20        Las Palmas      33  ...             2       -399    33.485401
20  21        Villarreal      17  ...             2        103    41.176471

[5 rows x 22 columns]


0  Pos   Team Seasons  ...  BestPosition  Goal_diff  Win_percent
56  57  Xerez       1  ...            20        -28    21.052632

[1 rows x 22 columns]
0  Pos   Team Seasons  ...  BestPosition  Goal_diff  Win_percent
56  57  Xerez       1  ...            20        -28    21.052632

[1 rows x 22 columns]


0  Pos      Team Seasons  ...  BestPosition  Goal_diff  Win_percent
6    7  Espanyol      82  ...             3       -280    36.100533
17  18    Oviedo      38  ...             3       -309    34.228188
18  19  Mallorca      27  ...             3       -189    33.704453
44  45    Arenas       7  ...             3        -81    33.076923

[4 rows x 22 columns]
0  Pos      Team Seasons  ...  BestPosition  Goal_diff  Win_percent
6    7  Espanyol      82  ...             3       -280    36.100533
17  18    Oviedo      38  ...             3       -309    34.228188
18  19  Mallorca      27  ...             3       -189    33.704453
44  45    Arenas       7  ...             3        -81    33.076923

[4 rows x 22 columns]


0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
11  12  Celta Vigo      51  ...             4       -346    34.511190
12  13  Valladolid      42  ...             4       -413    31.582538
15  16     Osasuna      37  ...             4       -334    32.321700
16  17      Malaga      36  ...             4       -342    31.075697
31  32    Sabadell      14  ...             4       -228    30.281690
34  35   Castellon      11  ...             4       -169    30.838323

[6 rows x 22 columns]
0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
11  12  Celta Vigo      51  ...             4       -346    34.511190
12  13  Valladolid      42  ...             4       -413    31.582538
15  16     Osasuna      37  ...             4       -334    32.321700
16  17      Malaga      36  ...             4       -342    31.075697
31  32    Sabadell      14  ...             4       -228    30.281690
34  35   Castellon      11  ...             4       -169    30.838323

[6 rows x 22 columns]


0  Pos      Team Seasons  ...  BestPosition  Goal_diff  Win_percent
23  24     Elche      21  ...             5       -272    29.941003
25  26  Hercules      20  ...             5       -334    29.299363
26  27  Tenerife      13  ...             5       -125    31.376518
37  38   Cordoba       9  ...             5       -145    29.078014

[4 rows x 22 columns]
0  Pos      Team Seasons  ...  BestPosition  Goal_diff  Win_percent
23  24     Elche      21  ...             5       -272    29.941003
25  26  Hercules      20  ...             5       -334    29.299363
26  27  Tenerife      13  ...             5       -125    31.376518
37  38   Cordoba       9  ...             5       -145    29.078014

[4 rows x 22 columns]


0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
21  22     Granada      23  ...             6       -338    29.380054
24  25      Getafe      12  ...             6       -113    32.236842
28  29      Alaves      12  ...             6       -165    32.894737
29  30     Levante      11  ...             6       -202    28.109453
51  52  Real Union       4  ...             6        -31    29.166667

[5 rows x 22 columns]
0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
21  22     Granada      23  ...             6       -338    29.380054
24  25      Getafe      12  ...             6       -113    32.236842
28  29      Alaves      12  ...             6       -165    32.894737
29  30     Levante      11  ...             6       -202    28.109453
51  52  Real Union       4  ...             6        -31    29.166667

[5 rows x 22 columns]


0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
30  31   Salamanca      12  ...             7       -159    29.078014
33  34    Logrones       9  ...             7       -198    27.745665
35  36    Albacete       7  ...             7        -90    28.148148
41  42  Pontevedra       6  ...             7        -56    29.444444
46  47   Gimnastic       4  ...             7       -114    29.310345

[5 rows x 22 columns]
0  Pos        Team Seasons  ...  BestPosition  Goal_diff  Win_percent
30  31   Salamanca      12  ...             7       -159    29.078014
33  34    Logrones       9  ...             7       -198    27.745665
35  36    Albacete       7  ...             7        -90    28.148148
41  42  Pontevedra       6  ...             7        -56    29.444444
46  47   Gimnastic       4  ...             7       -114    29.310345

[5 rows x 22 columns]


0  Pos            Team Seasons  ...  BestPosition  Goal_diff  Win_percent
22  23  Rayo Vallecano      17  ...             8       -328    28.987730
36  37         Almeria       6  ...             8       -122    27.192982
39  40      Recreativo       5  ...             8        -94    26.881720
53  54          Europa       3  ...             8        -34    33.333333

[4 rows x 22 columns]
0  Pos            Team Seasons  ...  BestPosition  Goal_diff  Win_percent
22  23  Rayo Vallecano      17  ...             8       -328    28.987730
36  37         Almeria       6  ...             8       -122    27.192982
39  40      Recreativo       5  ...             8        -94    26.881720
53  54          Europa       3  ...             8        -34    33.333333

[4 rows x 22 columns]


0  Pos         Team Seasons  ...  BestPosition  Goal_diff  Win_percent
45  46  Real Burgos       3  ...             9        -38    22.807018
60  61       Girona       1  ...             9          0     0.000000

[2 rows x 22 columns]
0  Pos         Team Seasons  ...  BestPosition  Goal_diff  Win_percent
45  46  Real Burgos       3  ...             9        -38    22.807018
60  61       Girona       1  ...             9          0     0.000000

[2 rows x 22 columns]